spring:
  application:
    name: personal-diary-mail-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'