spring:
  application:
    name: config-server
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            D:/MyProjects/PersonalDiary/personal-diary-config-properties/{application}/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lionchi/PersonalDiary/
          search-paths:
            - "personal-diary-config-properties/{application}/{profile}"
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

server:
  port: 8888