spring:
  application:
    name: personal-diary-authorization-service

server:
  port: 8740

eureka:
  client:
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8700/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'