spring:
  application:
    name: personal-diary-zull-client

server:
  port: 8710

eureka:
  client:
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8700/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    personal-diary-registration-service:
      path: /registration-api/**
      service-id: personal-diary-registration-service
    personal-diary-authorization-service:
      strip-prefix: false
      sensitive-headers: Authorization
      path: /auth/**
      service-id: personal-diary-authorization-service
    personal-diary-mail-service:
      path: /mail-api/**
      service-id: personal-diary-mail-service
    personal-diary-user-service:
      path: /user-api/**
      service-id: personal-diary-user-service
    personal-diary-service:
      path: /diary-api/**
      service-id: personal-diary-service
personal-diary-registration-service:
  ribbon:
    ReadTimeout: 35000
personal-diary-authorization-service:
  ribbon:
    ReadTimeout: 35000
personal-diary-user-service:
  ribbon:
    ReadTimeout: 35000
personal-diary-service:
  ribbon:
    ReadTimeout: 60000
personal-diary-mail-service:
  ribbon:
    ReadTimeout: 60000
