spring:
  application:
    name: personal-diary-zull-client
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  sleuth:
    sampler:
      probability: 100

server:
  port: 8710

eureka:
  client:
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8700/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    personal-diary-authorization-service:
      strip-prefix: false
      sensitive-headers: Authorization
      path: /auth/**
      service-id: personal-diary-authorization-service
    personal-diary-mail-service:
      path: /mail-api/**
      service-id: personal-diary-mail-service
    personal-diary-user-service:
      path: /user-api/**
      service-id: personal-diary-user-service
    personal-diary-service:
      path: /diary-api/**
      service-id: personal-diary-service
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 5000
personal:
  diary:
    swagger:
      docket:
        base-package: ru.jpixel.personaldiaryclient.web.controllers

