spring:
  application:
    name: personal-diary-zull-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
zuul:
  routes:
    personal-diary-registration-service:
      path: /registration-api/**
      service-id: personal-diary-registration-service
    personal-diary-authorization-service:
      strip-prefix: false
      sensitive-headers: Authorization
      path: /auth/**
      service-id: personal-diary-authorization-service
    personal-diary-mail-service:
      path: /mail-api/**
      service-id: personal-diary-mail-service
personal-diary-mail-service:
  ribbon:
    ReadTimeout: 60000
