spring:
  application:
    name: personal-diary-zull-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
zuul:
  routes:
    personal-diary-registration-service:
      path: /registration-api/**
      service-id: personal-diary-registration-service
    personal-diary-authorization-service:
      sensitive-headers: Cookie,Set-Cookie
      path: /auth-api/**
      service-id: personal-diary-authorization-service