spring:
  application:
    name: personal-diary-zull-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
zuul:
  routes:
    personal-diary-registration-service:
      path: /registration-api/**
    personal-diary-authorization-service:
      path: /auth/**
    personal-diary-mail-service:
      path: /mail-api/**
    personal-diary-user-service:
      path: /user-api/**
    personal-diary-service:
      path: /diary-api/**
