spring:
  application:
    name: personal-diary-eureka-server

server:
  port: 8700

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8700/eureka/}
  server:
    eviction-interval-timer-in-ms: 50000
    wait-time-in-ms-when-sync-empty: 5