FROM openjdk:14-jdk-alpine

ENV APP_FILE personal-diary-registration-service-1.0-SNAPSHOT.jar
ENV APP_HOME /usr/apps

EXPOSE 8720

COPY target/$APP_FILE $APP_HOME/

WORKDIR $APP_HOME

ENTRYPOINT ["sh", "-c"]

CMD ["exec java -jar -Dspring.profiles.active=prod $APP_FILE"]