spring:
  application:
    name: personal-diary-user-service
  jpa:
    hibernate:
      ddl-auto: validate
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  sleuth:
    sampler:
      probability: 100
  flyway:
    default-schema: secr
    schemas: secr

server:
  port: 8730

eureka:
  client:
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8700/eureka}
  instance:
    preferIpAddress: true
personal:
  diary:
    swagger:
      docket:
        base-package: ru.jpixel.personaldiaryuserservice.controllers
        paths:
---

spring:
  profiles: default,dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diary
    username: postgres
    password: root

---

spring:
  profiles: prod
  datasource:
    url: ${DIARY_BD_URL}
    username: ${DIARY_BD_USERNAME}
    password: ${DIARY_BD_PASSWORD}
    driver-class-name: org.postgresql.Driver