spring:
  application:
    name: personal-diary-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

---

spring:
  profiles: prod
  datasource:
    url: ${DIARY_BD_URL}
    username: ${DIARY_BD_USERNAME}
    password: ${DIARY_BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
