spring:
  application:
    name: personal-diary-service
  jpa:
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  sleuth:
    sampler:
      probability: 100

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  dashboard:
    proxy-stream-allow-list: '*'

server:
  port: 8760

eureka:
  client:
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8700/eureka}
  instance:
    preferIpAddress: true

encryption:
  algorithm: AES/ECB/PKCS5Padding
  key:
    algorithm: AES
    charset: GBK

---

spring:
  profiles: default,dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diary
    username: postgres
    password: root

---

spring:
  profiles: prod
  datasource:
    url: ${DIARY_BD_URL}
    username: ${DIARY_BD_USERNAME}
    password: ${DIARY_BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
